# Generated by Django 6.0.5 on 2026-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
