# Generated by Django 6.0.5 on 2026-05-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('raw_value', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'SCOPE_1'), ('SCOPE_2', 'SCOPE_2'), ('SCOPE_3', 'SCOPE_3')], max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FLAGGED', 'FLAGGED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
